# Generated by Django 5.0.2 on 2024-02-18 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='accounts',
            field=models.ManyToManyField(blank=True, related_name='accounts', to='account.account'),
        ),
    ]
