# Generated by Django 5.0.2 on 2024-02-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_account_users_remove_user_accounts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='accounts',
        ),
        migrations.AddField(
            model_name='account',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='accounts', to='account.user'),
        ),
    ]
