# Generated by Django 5.0.2 on 2024-02-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_user_accounts_account_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account',
            field=models.ManyToManyField(blank=True, related_name='accounts', to='account.account'),
        ),
    ]
