# Generated by Django 5.0.2 on 2024-02-19 06:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantedTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('planted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=16, max_digits=25, null=True, verbose_name='latitude')),
                ('location_long', models.DecimalField(blank=True, decimal_places=16, max_digits=25, null=True, verbose_name='longitude')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('scientific_name', models.CharField(max_length=150)),
                ('plantedTree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tree.plantedtree')),
            ],
        ),
    ]
