# Generated by Django 5.0.2 on 2024-02-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantedtree',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=25, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='plantedtree',
            name='location_long',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=25, null=True, verbose_name='longitude'),
        ),
    ]
