# Generated by Django 5.0.2 on 2024-02-18 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_account_users_alter_user_account'),
        ('tree', '0003_remove_tree_plantedtree_plantedtree_tree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantedtree',
            name='tree',
        ),
        migrations.AddField(
            model_name='tree',
            name='plantedTree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trees', to='tree.plantedtree'),
        ),
        migrations.AlterField(
            model_name='plantedtree',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.user'),
        ),
    ]
