# Generated by Django 5.0.2 on 2024-02-18 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0004_remove_plantedtree_tree_tree_plantedtree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='plantedTree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tree.plantedtree'),
        ),
    ]
